[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "qobuz-dl"
version = "0.9.9.10"
description = "The complete Lossless and Hi-Res music downloader for Qobuz"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pathvalidate",
    "requests",
    "mutagen",
    "tqdm",
    "pick==1.6.0",
    "beautifulsoup4",
    "colorama",
]

[project.scripts]
qobuz-dl = "qobuz_dl:main"
qdl = "qobuz_dl:main"

[dependency-groups]
dev = [
    "flake8",
    "ruff",
]

[tool.setuptools.packages.find]
include = ["qobuz_dl*"]

[tool.uv]
